version: 2
jobs:
  build:
    - image: coinberry/haskell:latest
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASS

    resource_class: large

    working_directory: /home/project

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: stack-blockchains-query-api-{{ checksum "stack.yaml" }}
      - restore_cache:
          key: stack-blockchains-query-api-final-{{ checksum "stack.yaml" }}
      - run: .circleci/setupenv.sh
      - run: stack build --only-dependencies
      - save_cache:
          key: stack-blockchains-query-api-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
            - ~/.local
      - run: .circleci/build.sh
      - run: .circleci/test.sh
      - save_cache:
          key: stack-blockchains-query-api-final-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
            - ~/.local
      - run: .circleci/lint.sh
      - persist_to_workspace:
          root: ~/.local/bin/
          paths: 
            - blockchains-query-api
      - store_artifacts:
          path: ~/.local/bin
          destination: blockchains-query-api

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
